# Generated by Django 5.2.8 on 2025-11-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=100, unique=True)),
                ('animal_type', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('vaccination_detail', models.TextField()),
            ],
        ),
    ]
