# Generated by Django 5.2.8 on 2025-12-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='vaccination_detail',
        ),
        migrations.AddField(
            model_name='animal',
            name='is_healthy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='required_vaccine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
