# Generated by Django 5.2.8 on 2025-12-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_animal_vaccination_detail_animal_is_healthy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_id',
        ),
    ]
