# Generated by Django 5.2.8 on 2026-03-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_farm'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.farm'),
        ),
    ]
