# Generated by Django 5.2.8 on 2026-03-11 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_farm_cascade_delete'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50)),
                ('animal_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('cause_of_death', models.CharField(choices=[('disease', 'Disease'), ('accident', 'Accident'), ('natural', 'Natural Causes'), ('predator', 'Predator Attack'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=50)),
                ('date_of_death', models.DateField()),
                ('age_at_death', models.CharField(max_length=50)),
                ('weight_at_death', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_record', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='farms.farm')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_death'],
            },
        ),
    ]
