# Generated by Django 5.2.8 on 2026-04-05 19:09

from django.conf import settings
from django.db import migrations, models


def backfill_user_animal_ids(apps, schema_editor):
    """Assign sequential user_animal_id to all existing animals, grouped by user."""
    Animal = apps.get_model('animals', 'Animal')
    # Process each user's animals in pk order
    user_ids = Animal.objects.values_list('user_id', flat=True).distinct()
    for user_id in user_ids:
        animals = Animal.objects.filter(user_id=user_id).order_by('pk')
        for counter, animal in enumerate(animals, start=1):
            animal.user_animal_id = counter
            animal.save(update_fields=['user_animal_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_mortalityrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='user_animal_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_user_animal_ids, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('user', 'user_animal_id')},
        ),
    ]
