# Generated by Django 5.2.8 on 2026-03-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('health', '0005_lameness_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='lameness_detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='health.lamenessdetection'),
        ),
    ]
