# Generated by Django 5.2.8 on 2026-04-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_environmentalalert_healthalert_vaccinationalert'),
        ('health', '0005_lameness_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_mtime', models.FloatField(help_text='os.path.getmtime() at scan time')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('detection_found', models.BooleanField(default=False)),
                ('predicted_result', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('output_path', models.CharField(blank=True, help_text='Path where detected file was copied', max_length=500)),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='alerts.detection')),
                ('lameness_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='health.lamenessdetection')),
            ],
            options={
                'verbose_name': 'Auto Scan Log',
                'verbose_name_plural': 'Auto Scan Logs',
                'ordering': ['-scanned_at'],
                'unique_together': {('file_path', 'file_mtime')},
            },
        ),
    ]
