from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q 
from .models import Animal 
from django.contrib.auth.decorators import login_required
from health.models import VaccineDataset # <-- NEW IMPORT



@login_required
@csrf_exempt
def add_animal(request):
    
    # NEW: Fetch unique vaccine names for the dropdown
    available_vaccines = list(VaccineDataset.objects.values_list('vaccine_name', flat=True).distinct().order_by('vaccine_name'))

    if request.method == 'POST':
        # ID is now autogenerated, we only fetch the necessary fields
        # a_id is removed from POST data fetching.
        a_type = request.POST.get('type')
        a_age = request.POST.get('age')
        a_sex = request.POST.get('sex')
        
        # NEW FIELDS
        is_healthy_str = request.POST.get('is_healthy')
        required_vaccine = request.POST.get('required_vaccine')
        
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        
        # Convert checkbox value to boolean
        is_healthy = is_healthy_str == 'on'
        
        # Validation checks
        if not all([a_type, a_age, a_sex]):
            msg = 'Please fill out all required fields.'
            if is_ajax:
                return JsonResponse({'status': 'error', 'message': msg})
            messages.error(request, msg)
            return redirect('animals:add_animal')

        # Conditional validation for vaccine
        if not is_healthy and not required_vaccine:
            msg = 'If the animal is not healthy, please select the required vaccine.'
            if is_ajax:
                return JsonResponse({'status': 'error', 'message': msg})
            messages.error(request, msg)
            return redirect('animals:add_animal')
        
        # Ensure required_vaccine is NULL/empty if the animal is healthy
        if is_healthy:
            required_vaccine = None
            
        try:
            # The animal_id will be autogenerated in the save method of the Animal model
            new_animal = Animal.objects.create(
                user=request.user, 
                animal_type=a_type,
                age=a_age,
                sex=a_sex,
                is_healthy=is_healthy, # NEW
                required_vaccine=required_vaccine # NEW
            )
            
            # The save method will trigger generate_unique_id()
            new_animal.save() 
            
            if is_ajax:
                return JsonResponse({'status': 'success', 'message': f'Animal {new_animal.animal_id} added successfully!'})
            messages.success(request, f'Animal {new_animal.animal_id} added successfully!')
            return redirect('accounts:home')
            
        except Exception as e:
            if is_ajax:
                return JsonResponse({'status': 'error', 'message': f"An unexpected error occurred: {e}"})
            messages.error(request, f"An unexpected error occurred: {e}")
            return redirect('animals:add_animal')

    else:
        context = {
            'available_vaccines': available_vaccines
        }
        return render(request, 'add_animal.html', context)

@login_required # Added login_required so we can access request.user safely
def search_animal(request):
    # Start with an empty queryset
    animals = Animal.objects.none()  
    query_set = {}

    try:
        # UPDATED: Only fetch animals belonging to the current user
        animals = Animal.objects.filter(user=request.user)

        if request.method == 'POST':
            filters = Q()
            animal_id = request.POST.get('animal_id')
            if animal_id:
                filters &= Q(animal_id__icontains=animal_id)
                query_set['Animal ID'] = animal_id

            animal_type = request.POST.get('type')
            if animal_type:
                filters &= Q(animal_type__icontains=animal_type)
                query_set['Type'] = animal_type
            
            sex = request.POST.get('sex')
            if sex:
                filters &= Q(sex__iexact=sex)
                query_set['Sex'] = sex
            
            age = request.POST.get('age')
            if age:
                filters &= Q(age__exact=age)
                query_set['Age'] = age

            # Apply the combined filters to the user's animals
            animals = animals.filter(filters)
            
            if not animals.exists():
                messages.info(request, "No animals matched your search criteria.")
    
    except Exception as e:
        messages.error(request, f"A database error occurred: {e}")
        return redirect('accounts:home')

    context = {
        'animals': animals,
        'filters': query_set,
    }
    return render(request, 'search_animal.html', context)

def select_method(request):
    """Renders the page to choose between Manual or Auto"""
    return render(request, 'select_method.html')

def auto_add(request):
    """Renders the RFID/Camera simulation page"""
    return render(request, 'auto_add.html')