# Generated by Django 5.2.8 on 2025-11-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_alter_animal_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('schedule_date', models.DateField()),
                ('dose_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
