# Generated by Django 5.2.8 on 2025-12-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Cow', 'Cow'), ('Goat', 'Goat'), ('Sheep', 'Sheep')], max_length=50)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
                ('min_age_months', models.FloatField(default=0, help_text='Minimum age in months')),
                ('dosage_frequency', models.CharField(max_length=100)),
                ('seasonality', models.CharField(blank=True, max_length=100, null=True)),
                ('booster_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('mandatory_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
