# Generated by Django 5.2.8 on 2025-12-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_vaccinedataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationschedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
