# Generated by Django 5.2.8 on 2026-03-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_vaccinationschedule_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinedataset',
            options={'ordering': ['animal_species', 'disease_name'], 'verbose_name': 'Vaccine Dataset Entry', 'verbose_name_plural': 'Vaccine Dataset Entries'},
        ),
        migrations.RemoveField(
            model_name='vaccinedataset',
            name='booster_rule',
        ),
        migrations.RemoveField(
            model_name='vaccinedataset',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='vaccinedataset',
            name='dosage_frequency',
        ),
        migrations.RemoveField(
            model_name='vaccinedataset',
            name='mandatory_conditions',
        ),
        migrations.RemoveField(
            model_name='vaccinedataset',
            name='min_age_months',
        ),
        migrations.RemoveField(
            model_name='vaccinedataset',
            name='seasonality',
        ),
        migrations.RemoveField(
            model_name='vaccinedataset',
            name='species',
        ),
        migrations.AddField(
            model_name='vaccinedataset',
            name='age_at_first_dose',
            field=models.CharField(blank=True, help_text="e.g. '6-8 weeks', '40-60 days prior to calving'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedataset',
            name='animal_species',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Cattle, Buffalo', 'Calves', 'Sheep & Goats'", max_length=255),
        ),
        migrations.AddField(
            model_name='vaccinedataset',
            name='booster_dose',
            field=models.CharField(blank=True, help_text='Booster dose schedule if applicable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedataset',
            name='disease_name',
            field=models.CharField(default='', help_text="e.g. 'FMD Foot and Mouth Disease'", max_length=255),
        ),
        migrations.AddField(
            model_name='vaccinedataset',
            name='related_information',
            field=models.TextField(blank=True, help_text='Dosage, type, manufacturer info from dataset', null=True),
        ),
        migrations.AddField(
            model_name='vaccinedataset',
            name='subsequent_dose',
            field=models.CharField(blank=True, help_text="e.g. 'Annual', 'Every 6 months'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedataset',
            name='vaccination_season',
            field=models.CharField(blank=True, help_text="e.g. 'FEB-MAR SEP-OCT', 'Spring', 'Annual'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinedataset',
            name='vaccine_name',
            field=models.CharField(default='', help_text="e.g. 'Inactivated FMD vaccine'", max_length=255),
        ),
        migrations.AlterModelTable(
            name='vaccinedataset',
            table='vaccine_dataset',
        ),
    ]
