# Generated by Django 5.2.8 on 2026-03-09 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_farm'),
        ('health', '0004_alter_vaccinedataset_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LamenessDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='detections/lameness/')),
                ('predicted_result', models.CharField(choices=[('normal', 'Normal'), ('lameness', 'Lameness Detected')], default='normal', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('all_probabilities', models.JSONField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('frames_sampled', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lameness_detections', to='animals.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lameness_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
